export const TYPES = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_PRODUCT_LOAD: "GET_PRODUCT_LOAD",
  GET_PRODUCT_SUCCEDD: "GET_PRODUCT_SUCCEDD",
  GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
  GET_PRODUCT_LOGOUT: "GET_PRODUCT_LOGOUT",
  GET_TOKEN_SUCCEDD: "GET_TOKEN_SUCCEDD",
  GET_TOKEN_LOAD: "GET_TOKEN_LOAD",
  GET_TOKEN_FAIL: "GET_TOKEN_FAIL",
  LOGOUT_SUCCEDD: "LOGOUT_SUCCEDD",
};
